-- Paper trading portfolio tables
-- Run in Supabase SQL editor

CREATE TABLE IF NOT EXISTS portfolio (
  id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id     UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  cash_balance NUMERIC(14, 2) NOT NULL DEFAULT 100000,
  UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS positions (
  id       BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id  UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  symbol   VARCHAR(20) NOT NULL,
  shares   NUMERIC(20, 10) NOT NULL,
  avg_cost NUMERIC(20, 6) NOT NULL,
  UNIQUE (user_id, symbol)
);

CREATE TABLE IF NOT EXISTS trades (
  id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id     UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  symbol      VARCHAR(20) NOT NULL,
  action      VARCHAR(4) NOT NULL CHECK (action IN ('buy', 'sell')),
  shares      NUMERIC(20, 10) NOT NULL,
  price       NUMERIC(14, 2) NOT NULL,
  total       NUMERIC(14, 2) NOT NULL,
  executed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_portfolio_user    ON portfolio(user_id);
CREATE INDEX IF NOT EXISTS idx_positions_user    ON positions(user_id);
CREATE INDEX IF NOT EXISTS idx_trades_user_time  ON trades(user_id, executed_at DESC);

-- Enable Row Level Security
ALTER TABLE portfolio ENABLE ROW LEVEL SECURITY;
ALTER TABLE positions ENABLE ROW LEVEL SECURITY;
ALTER TABLE trades    ENABLE ROW LEVEL SECURITY;

-- RLS policies: each user can only access their own rows
CREATE POLICY "portfolio_owner" ON portfolio
  USING (user_id = auth.uid());

CREATE POLICY "positions_owner" ON positions
  USING (user_id = auth.uid());

CREATE POLICY "trades_owner" ON trades
  USING (user_id = auth.uid());
